## Task 16

### Linear Algebra

Given 2 matrices,\
Let

$$
A = \begin{bmatrix}
2 & -1 \\
0 & 3
\end{bmatrix}
$$


$$
B = \begin{bmatrix}
1 & 4 \\
-2 & 5
\end{bmatrix}
$$

And the scalers (c = 2), (d = 3)

a. Compute the following: (cA), (dB), and (c + d)A
b. using the results gotten, verify the scalar multiplication
c. find the transpose of both matrices
d. check if (A) and (B) are invertible by computing the determinants. if they are invertible, find $$ A^{-1} $$ and $$ B^{-1} $$

In [4]:
import numpy as np

# Defining matrix parameters
A = np.array([[2, -1],
              [0, 3]])

B = np.array([[1, 4],
              [-2, 5]])

# Defining scalar
c, d = 2, 3

print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
print(f"c = {c} and d = {d}")

Matrix A:
[[ 2 -1]
 [ 0  3]]
Matrix B:
[[ 1  4]
 [-2  5]]
c = 2 and d = 3


##### a.

In [ ]:
# Computing cA
cA = c * A

# Computing cB
dB = d * B

# Computing (c + d)A
add = (c + d) * A

print(f"cA is:\n {cA}")
print(f"dB is:\n {dB}")
print(f"(c + d)A is:\n {add}")


cA is:
 [[ 4 -2]
 [ 0  6]]
dB is:
 [[ 3 12]
 [-6 15]]
(c + d)A is:
 [[10 -5]
 [ 0 15]]


#### b.

In [27]:
# Scalar Multiplication Properties
# Scalar multiplication properties are
# Associativity of sclar multiplication: (c.d)A = c.(dA)
# Distributivity over matrix addition: c(A + B) = cA + cB
# Distributivity over scalar addition: (c + d)A = cA + dA

# Associativity of Scalar Multiplication
left = (c * d) * A
right = c * (d * A)

print(f"(c x d)A = \n{left}")
print(f"c(dA) = \n{right}")
print(f"Associativity of Scalar Multiplication: \n(c.d)A = c.(dA) is {np.array_equal(left, right)}")





(c x d)A = 
[[12 -6]
 [ 0 18]]
c(dA) = 
[[12 -6]
 [ 0 18]]
Associativity of Scalar Multiplication: 
(c.d)A = c.(dA) is True


In [25]:
# Distributivity over matrix addition
dist_left = c * (A + B)
dist_right = c * A + c * B

print(f"c(A + B) = \n{dist_left}")
print(f"cA + cB = \n{dist_right}")
print(f"Distributivity over Matrix addition: \nc(A + B) = cA + cB is {np.array_equal(dist_left, dist_right)}")

c(A + B) = 
[[ 6  6]
 [-4 16]]
cA + cB = 
[[ 6  6]
 [-4 16]]
Distributivity over Matrix addition: 
c(A + B) = cA + cB is True


In [26]:
# Distributivity over scalar 
scalar_left = (c + d) * A
scalar_right = c*A + d*A

print(f"(c + d)A = \n{scalar_left}")
print(f"cA + dA = \n{scalar_right}")
print(f"Distributivity over Scalar addition: \n(c + d)A = cA + dA is {np.array_equal(scalar_left, scalar_right)}")

(c + d)A = 
[[10 -5]
 [ 0 15]]
cA + dA = 
[[10 -5]
 [ 0 15]]
Distributivity over Scalar addition: 
(c + d)A = cA + dA is True


#### c.

In [9]:
# Transpose of Matrix A
print(f"Transpose of Matrix A:\n {A.T}")

# Transpose of Matrix B
print(f"Transpose of Matrix B:\n {B.T}")

Transpose of Matrix A:
 [[ 2  0]
 [-1  3]]
Transpose of Matrix B:
 [[ 1 -2]
 [ 4  5]]


#### d.

In [36]:
# Tocheck for A and B invertibility using Determinant

detA = np.linalg.det(A)
print(f" Determinant of Matrix A : \n{detA}")
print(f"Is it invertible: {detA != 0}\n")


detB = np.linalg.det(B)
print(f" Determinant of Matrix B : \n{detB}")
print(f"Is it invertible: {detB != 0}\n")
print(f"Since Matrix A and B are invertible, we can find the inverse")

# Since det(A) and det(B) != 0, Matrix A and B are invertible

 Determinant of Matrix A : 
6.0
Is it invertible: True

 Determinant of Matrix B : 
13.0
Is it invertible: True

Since Matrix A and B are invertible, we can find the inverse


In [38]:
# inverse of Matrix A
print(f"The inverse of Matrix A is \n{np.linalg.inv(A)}")

# inverse of Matrix B
print(f"The inverse of Matrix B is \n{np.linalg.inv(B)}")

The inverse of Matrix A is 
[[0.5        0.16666667]
 [0.         0.33333333]]
The inverse of Matrix B is 
[[ 0.38461538 -0.30769231]
 [ 0.15384615  0.07692308]]
