## Task 16

### Linear Algebra

Given 2 matrices,\
Let

$$
A = \begin{bmatrix}
2 & -1 \\
0 & 3
\end{bmatrix}
$$


$$
B = \begin{bmatrix}
1 & 4 \\
-2 & 5
\end{bmatrix}
$$

And the scalers (c = 2), (d = 3)

a. Compute the following: (cA), (dB), and (c + d)A
b. using the results gotten, verify the scalar multiplication
c. find the transpose of both matrices
d. check if (A) and (B) are invertible by computing the determinants. if they are invertible, find $$ A^{-1} $$ and $$ B^{-1} $$

In [4]:
import numpy as np

# Defining matrix parameters
A = np.array([[2, -1],
              [0, 3]])

B = np.array([[1, 4],
              [-2, 5]])

# Defining scalar
c, d = 2, 3

print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
print(f"c = {c} and d = {d}")

Matrix A:
[[ 2 -1]
 [ 0  3]]
Matrix B:
[[ 1  4]
 [-2  5]]
c = 2 and d = 3


##### a.

In [ ]:
# Computing cA
cA = c * A

# Computing cB
dB = d * B

# Computing (c + d)A
add = (c + d) * A

print(f"cA is:\n {cA}")
print(f"dB is:\n {dB}")
print(f"(c + d)A is:\n {add}")


cA is:
 [[ 4 -2]
 [ 0  6]]
dB is:
 [[ 3 12]
 [-6 15]]
(c + d)A is:
 [[10 -5]
 [ 0 15]]


#### b.

In [25]:
# Scalar Multiplication Properties
# Scalar multiplication properties are
# Associativity of sclar multiplication: (c.d)A = c.(dA)
# Distributivity over matrix addition: c(A + B) = cA + cB
# Distributivity over scalar addition: (c + d)A = cA + dA

# Associativity of Scalar Multiplication
left = (c * d) * A
right = c * (d * A)

# Distributivity over matrix addition
dist_left = c * (A + B)
dist_right = c * A + c * B


# Distributivity over scalar 
scalar_left = (c + d) * A
scalar_right = c*A + d*A

print(f"Associativity of Scalar Multiplication: \n(c.d)A = c.(dA) is {np.array_equal(left, right)}")
print(f"Distributivity over Matrix addition: \nc(A + B) = cA + cB is {np.array_equal(dist_left, dist_right)}")
print(f"Distributivity over Scalar addition: \n(c + d)A = cA + dA is {np.array_equal(scalar_left, scalar_right)}")


Associativity of Scalar Multiplication: 
(c.d)A = c.(dA) is True
Distributivity over Matrix addition: 
c(A + B) = cA + cB is True
Distributivity over Scalar addition: 
(c + d)A = cA + dA is True
