## Task 16

### Linear Algebra

Given 2 matrices,\
Let

$$
A = \begin{bmatrix}
2 & -1 \\
0 & 3
\end{bmatrix}
$$


$$
B = \begin{bmatrix}
1 & 4 \\
-2 & 5
\end{bmatrix}
$$

And the scalers (c = 2), (d = 3)

a. Compute the following: (cA), (dB), and (c + d)A
b. using the results gotten, verify the scalar multiplication
c. find the transpose of both matrices
d. check if (A) and (B) are invertible by computing the determinants. if they are invertible, find $$ A^{-1} $$ and $$ B^{-1} $$

In [4]:
import numpy as np

# Defining matrix parameters
A = np.array([[2, -1],
              [0, 3]])

B = np.array([[1, 4],
              [-2, 5]])

# Defining scalar
c, d = 2, 3

print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
print(f"c = {c} and d = {d}")

Matrix A:
[[ 2 -1]
 [ 0  3]]
Matrix B:
[[ 1  4]
 [-2  5]]
c = 2 and d = 3


##### a.

In [ ]:
# Computing cA
cA = c*A
print(f"cA is:\n {cA}")

# Computing cB
dB = d*B
print(f"dB is:\n {dB}")

# Computing (c + d)A


cA is:
 [[ 4 -2]
 [ 0  6]]
dB is:
 [[ 3 12]
 [-6 15]]
